name: Docker Build/Publish Preview Image from PR
on:
  pull_request:
    branches:
    - main
  workflow_dispatch: {}

jobs:
  build:
    uses: sfudeus/workflows/.github/workflows/docker-build-publish-pr.yaml@main
    secrets: inherit
    with:
      tag: preview-${{ github.event.number }}
      platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
