name: Docker Build/Publish Release
on:
  push:
    tags:
    - "*"

jobs:
  build:
    uses: sfudeus/workflows/.github/workflows/docker-build-publish-tag.yaml@main
    secrets: inherit
    with:
      platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
