name: Docker Build/Publish Preview Image from branch
on:
  pull_request:
    branches:
    - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Define revision
      id: revision
      run: |
        echo "target-revision=preview-${{ github.event.number }}" >> $GITHUB_OUTPUT
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker build/push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
        tags: |
          "${{ github.repository }}:${{ steps.revision.outputs.target-revision }}"
        push: true
    - name: Comment docker repo
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Preview available at docker.io/' + "${{ github.repository }}:${{ steps.revision.outputs.target-revision }}"
          })
